#!/usr/bin/env bash
# Rebrand progress report — machine verification for Phase 0 + cleanup passes A–E.
# See .cursor/specs/core/03-zed-reference-cleanup-phases.md#progress
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

FULL=0
MARKDOWN=0
QUIET=0

usage() {
  cat <<'EOF'
Usage: ./script/rebrand-progress.sh [OPTIONS]

Reports automated rebrand gate status. Use after completing work on a pass,
then update checkboxes in 03-zed-reference-cleanup-phases.md#progress.

Options:
  --full       Also run ./script/qa-p0.sh (slow; ~1 min)
  --markdown   Emit a markdown snippet suitable for pasting into the Progress section
  --quiet      Only print failures and summary line

Set QA_NETWORK_IDLE=1 with --full to also run ./script/network-idle-audit.sh (~90s).
  -h, --help   Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --full) FULL=1; shift ;;
    --markdown) MARKDOWN=1; shift ;;
    --quiet) QUIET=1; shift ;;
    -h | --help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

log() {
  if [[ "$QUIET" -eq 0 ]]; then
    echo "$@"
  fi
}

summary() {
  echo "$@"
}

section_passed() {
  local start="$1"
  local end="$2"
  local block
  block=$(awk "/^${start}\$/,/^${end}\$/ { if (\$0 !~ /^${start}\$/ && \$0 !~ /^${end}\$/) print }" "$LOG")
  if [[ -z "$block" ]]; then
    return 1
  fi
  if printf '%s\n' "$block" | grep -q '^✗'; then
    return 1
  fi
  printf '%s\n' "$block" | grep -q '^✓'
}

count_section() {
  local start="$1"
  local end="$2"
  local block ok fail
  block=$(awk "/^${start}\$/,/^${end}\$/ { if (\$0 !~ /^${start}\$/ && \$0 !~ /^${end}\$/) print }" "$LOG")
  ok=$(printf '%s\n' "$block" | grep -c '^✓' || true)
  fail=$(printf '%s\n' "$block" | grep -c '^✗' || true)
  echo "${ok}:${fail}"
}

LOG="$(mktemp -t rebrand-progress.XXXXXX)"
trap 'rm -f "$LOG"' EXIT

log "CueCode rebrand progress"
log "========================"
log "Running ./script/rebrand-check.sh …"

if ./script/rebrand-check.sh >"$LOG" 2>&1; then
  REBRAND_EXIT=0
else
  REBRAND_EXIT=$?
fi

if [[ "$MARKDOWN" -eq 0 && "$QUIET" -eq 0 ]]; then
  cat "$LOG"
  echo ""
fi

QA_EXIT=""
QA_SUMMARY=""
if [[ "$FULL" -eq 1 ]]; then
  log "Running ./script/qa-p0.sh …"
  QA_LOG="$(mktemp -t qa-p0-progress.XXXXXX)"
  if ./script/qa-p0.sh >"$QA_LOG" 2>&1; then
    QA_EXIT=0
  else
    QA_EXIT=$?
  fi
  QA_SUMMARY=$(grep -E '^Pass:|^Fail:' "$QA_LOG" | tail -1 || true)
  if [[ "$QUIET" -eq 0 ]]; then
    tail -8 "$QA_LOG"
    echo ""
  fi
  rm -f "$QA_LOG"
fi

NETWORK_EXIT=""
if [[ "$FULL" -eq 1 && "${QA_NETWORK_IDLE:-0}" == "1" ]]; then
  log "Running ./script/network-idle-audit.sh …"
  if ./script/network-idle-audit.sh; then
    NETWORK_EXIT=0
  else
    NETWORK_EXIT=$?
  fi
fi

pass_a=$(count_section "Pass A — settings and keymap comments:" "Pass B — remaining user-visible strings:")
pass_b=$(count_section "Pass B — remaining user-visible strings:" "Pass C — filename and artifact renames:")
pass_c=$(count_section "Pass C — filename and artifact renames:" "Pass D — docs and legal:")
pass_d=$(count_section "Pass D — docs and legal:" "L3.1 — cuecode_actions crate rename:")

status_icon() {
  local counts="$1"
  local ok="${counts%%:*}"
  local fail="${counts##*:}"
  if [[ "$fail" -gt 0 ]]; then
    echo "FAIL ($ok ok, $fail fail)"
  elif [[ "$ok" -gt 0 ]]; then
    echo "PASS ($ok gates)"
  else
    echo "UNKNOWN"
  fi
}

DOCS_ZED=$(rg -n '\bZed\b' docs/ 2>/dev/null | grep -vc 'upstream Zed staff only' || true)
DOCS_ZED=${DOCS_ZED:-0}

VERIFIED_AT="$(date -u +%Y-%m-%d)"

final_exit=$REBRAND_EXIT
if [[ "$FULL" -eq 1 && "${QA_EXIT:-0}" -ne 0 ]]; then
  final_exit=1
fi
if [[ "$FULL" -eq 1 && "${QA_NETWORK_IDLE:-0}" == "1" && "${NETWORK_EXIT:-0}" -ne 0 ]]; then
  final_exit=1
fi

if [[ "$MARKDOWN" -eq 1 ]]; then
  cat <<EOF
<!-- generated by ./script/rebrand-progress.sh — paste into #progress, then curate manual items -->
**Last verified:** ${VERIFIED_AT} (\`./script/rebrand-progress.sh --full\`)

| Gate bundle | Status |
|-------------|--------|
| \`rebrand-check.sh\` | $([[ "$REBRAND_EXIT" -eq 0 ]] && echo 'green' || echo "**FAILED**") |
| Pass A | $(status_icon "$pass_a") |
| Pass B | $(status_icon "$pass_b") |
| Pass C | $(status_icon "$pass_c") |
| Pass D | $(status_icon "$pass_d") |
| \`docs/\` bare \`Zed\` hits (excl. allowlist) | ${DOCS_ZED} |
$([[ "$FULL" -eq 1 ]] && echo "| \`qa-p0.sh\` | $([[ "$QA_EXIT" -eq 0 ]] && echo 'green' || echo "**FAILED**") ($QA_SUMMARY) |")
$([[ "$FULL" -eq 1 && "${QA_NETWORK_IDLE:-0}" == "1" ]] && echo "| \`network-idle-audit.sh\` | $([[ "$NETWORK_EXIT" -eq 0 ]] && echo 'green' || echo "**FAILED**") |")
EOF
  exit "$final_exit"
fi

summary "Summary"
summary "-------"
summary "rebrand-check.sh: $([[ "$REBRAND_EXIT" -eq 0 ]] && echo PASS || echo FAIL)"
summary "Pass A: $(status_icon "$pass_a")"
summary "Pass B: $(status_icon "$pass_b")"
summary "Pass C: $(status_icon "$pass_c")"
summary "Pass D: $(status_icon "$pass_d")"
summary "docs/ bare Zed (non-allowlist): ${DOCS_ZED}"
if [[ "$FULL" -eq 1 ]]; then
  summary "qa-p0.sh: $([[ "$QA_EXIT" -eq 0 ]] && echo PASS || echo FAIL) ${QA_SUMMARY}"
fi
if [[ "$FULL" -eq 1 && "${QA_NETWORK_IDLE:-0}" == "1" ]]; then
  summary "network-idle-audit.sh: $([[ "$NETWORK_EXIT" -eq 0 ]] && echo PASS || echo FAIL)"
fi
summary ""
summary "Update checkboxes: .cursor/specs/core/03-zed-reference-cleanup-phases.md#progress"
summary "Sub-phase docs: .cursor/specs/delivery/build-plans/phases/"
summary "Roadmap rollup: .cursor/specs/delivery/07-implementation-roadmap.md#progress"
summary "Skill: .cursor/skills/rebrand-progress/SKILL.md"

exit "$final_exit"
